// UI Text Constants - No hardcoded strings in components
export const UI_TEXT = {
  brand: {
    name: "Acadexis",
    tagline: "Institutional AI Knowledge Grounding",
    description: "Bridge the gap between university lecturers, students, and AI with grounded, citation-backed learning.",
  },
  landing: {
    heroTitle: "Where Academic Knowledge Meets Intelligent AI",
    heroSubtitle: "Acadexis empowers lecturers to ground AI in their curriculum, giving students AI-powered study sessions backed by verified course materials.",
    ctaPrimary: "Get Started Free",
    ctaSecondary: "See How It Works",
    features: [
      {
        title: "AI-Grounded Study Lab",
        description: "Students chat with AI that references uploaded course PDFs with precise page citations.",
        icon: "brain" as const,
      },
      {
        title: "Struggle Heatmaps",
        description: "Lecturers see exactly where students struggle, powered by real-time AI interaction analytics.",
        icon: "chart" as const,
      },
      {
        title: "Knowledge Hub",
        description: "Upload, organize, and manage course materials that become the AI's source of truth.",
        icon: "upload" as const,
      },
      {
        title: "Institutional Control",
        description: "Universities maintain full control over what the AI knows and how it responds.",
        icon: "shield" as const,
      },
    ],
    stats: [
      { value: "50+", label: "Universities" },
      { value: "12K+", label: "Students" },
      { value: "98%", label: "Citation Accuracy" },
      { value: "2M+", label: "Study Sessions" },
    ],
  },
  auth: {
    loginTitle: "Welcome Back",
    loginSubtitle: "Sign in to continue your learning journey",
    registerTitle: "Join Acadexis",
    registerSubtitle: "Create your account to get started",
    emailLabel: "Email Address",
    passwordLabel: "Password",
    confirmPasswordLabel: "Confirm Password",
    firstNameLabel: "First Name",
    lastNameLabel: "Last Name",
    idNumberLabel: "Identification Number",
    roleLabel: "I am a...",
    universityLabel: "University",
    facultyLabel: "Faculty",
    departmentLabel: "Department",
    levelLabel: "Level / Year",
    loginButton: "Sign In",
    registerButton: "Create Account",
    forgotPassword: "Forgot your password?",
    noAccount: "Don't have an account?",
    hasAccount: "Already have an account?",
    signUp: "Sign Up",
    signIn: "Sign In",
  },
  dashboard: {
    welcomeBack: "Welcome back",
    overview: "Overview",
    dashboard: "Dashboard",
    courses: "Courses",
    manageCourses: "Manage Courses",
    myCourses: "My Courses",
    myLibrary: "My Library",
    courseCatalog: "Course Catalog",
    studyAnalytics: "Study Analytics",
    bookmarks: "Bookmarks",
    aggregate: "Aggregate",
    studyLab: "The Study Lab",
    knowledgeHub: "Knowledge Hub",
    uploads: "Uploads",
    manageStudents: "Manage Students",
    analytics: "Analytics",
    heatmap: "Struggle Heatmap",
    createCourse: "Create Course",
    profile: "Profile",
    settings: "Settings",
    notifications: "Notifications",
    contact: "Contact Team",
    report: "Report Issue",
    helpSupport: "Help & Support",
    adminRequest: "Request Admin",
    search: "Search courses, materials...",
    logout: "Sign Out",
  },
  studyLab: {
    title: "The Study Lab",
    subtitle: "Chat with AI grounded in your course materials",
    askPlaceholder: "Ask about your course material...",
    sourceTag: "Source",
    pageRef: "Page",
    aiThinking: "Analyzing your course materials...",
  },
  notifications: {
    title: "Notifications",
    markAllRead: "Mark all as read",
    noNotifications: "You're all caught up!",
  },
  common: {
    loading: "Loading...",
    save: "Save Changes",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    view: "View",
    upload: "Upload",
    download: "Download",
    submit: "Submit",
    back: "Back",
    next: "Next",
    processing: "Processing...",
  },
} as const;
